on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Pod Install
        run: pod install
      - name: Build and Test
        run: xcodebuild clean test -workspace blyp.xcworkspace -scheme blyp -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
