on: [pull_request]
name: Test PR
jobs:
  test:
    name: Test PR
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.4,name=iPhone 11']
    steps:
      - name: Check out merge commit of pull request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Pod Install
        run: pod install
      - name: Build and Test
        run: xcodebuild clean test -workspace blyp.xcworkspace -scheme blyp -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
